import { Category } from "../types"; // adjust the import path

// Dummy categories
export const categories: Category[] = [
  {
    id: "cat-1",
    created_at: "2025-09-24T10:00:00.000Z",
    updated_at: "2025-09-24T10:00:00.000Z",
    deleted_at: null,
    createdBy: "admin-1",
    name: "Web Development",
    slug: "web-development",
    description: "Learn how to build modern and scalable web applications.",
    image: "",
    parent: null,
    subcategories: [],
    coursesNumber: 43,
  },
  {
    id: "cat-2",
    created_at: "2025-09-24T11:00:00.000Z",
    updated_at: "2025-09-24T11:00:00.000Z",
    deleted_at: null,
    createdBy: "admin-3",
    name: "Data Science",
    slug: "data-science",
    description: "Explore data analysis, visualization, and machine learning.",
    image: "",
    parent: null,
    subcategories: [],
    coursesNumber: 32,
  },
  {
    id: "cat-3",
    created_at: "2025-09-24T10:05:00.000Z",
    updated_at: "2025-09-24T10:05:00.000Z",
    deleted_at: null,
    createdBy: "admin-1",
    name: "Frontend",
    slug: "frontend",
    description: "Courses on HTML, CSS, JavaScript, and frameworks like React.",
    image: "",
    parent: null,
    subcategories: [],
    coursesNumber: 25,
  },
  {
    id: "cat-4",
    created_at: "2025-09-24T10:06:00.000Z",
    updated_at: "2025-09-24T10:06:00.000Z",
    deleted_at: null,
    createdBy: "admin-2",
    name: "Backend",
    slug: "backend",
    description: "Courses on Node.js, NestJS, databases, and APIs.",
    image: "",
    parent: null,
    subcategories: [],
    coursesNumber: 18,
  },
];
