import { Quiz } from "@/types/quiz";
import { instructors } from "./instructors.data";

export const quizzes: Quiz[] = [
  {
    id: "1",
    title: "World Capitals Quiz",
    instructions:
      "Test your knowledge of world capitals. Select the correct answer for each question.",
    randomizeQuestions: false,
    immediateFeedback: true,
    feedbackByEmail: false,
    timeLimit: 120,
    passingScore: 70,
    retakeNumbers: 3,
    instructor: instructors[0],
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        text: "What is the capital of Japan?",
        points: 5,
        options: [
          { id: "q1-o1", text: "Seoul", isCorrect: false },
          { id: "q1-o2", text: "Tokyo", isCorrect: true },
          { id: "q1-o3", text: "Beijing", isCorrect: false },
          { id: "q1-o4", text: "Bangkok", isCorrect: false },
        ],
        explanation: "Tokyo is the capital and largest city of Japan.",
        answerCorrect: 1,
      },
      {
        id: "q2",
        type: "true-false",
        text: "Canberra is the capital of Australia.",
        points: 3,
        options: [
          { id: "q2-true", text: "True", isCorrect: true },
          { id: "q2-false", text: "False", isCorrect: false },
        ],
        explanation: "Canberra has been the capital of Australia since 1913.",
        answerCorrect: 0,
      },
    ],
    avarageScore: 60,
    takeTime: "flexible",
    questionsOrder: "random",
  },
  {
    id: "2",
    title: "Basic Mathematics",
    instructor: instructors[2],
    instructions:
      "Solve these basic math problems. You have 90 seconds per question.",
    randomizeQuestions: true,
    immediateFeedback: false,
    feedbackByEmail: true,
    timeLimit: 90,
    passingScore: 80,
    retakeNumbers: 2,
    questions: [
      {
        id: "q3",
        type: "multiple-choice",
        text: "What is 12 × 5?",
        points: 5,
        options: [
          { id: "q3-o1", text: "50", isCorrect: false },
          { id: "q3-o2", text: "60", isCorrect: true },
          { id: "q3-o3", text: "72", isCorrect: false },
          { id: "q3-o4", text: "48", isCorrect: false },
        ],
        explanation: "12 multiplied by 5 equals 60.",
        answerCorrect: 1,
      },
      {
        id: "q4",
        type: "fill-in-the-blank",
        text: "Solve for x: 3x + 7 = 22",
        points: 10,
        explanation:
          "Subtract 7 from both sides: 3x = 15, then divide by 3: x = 5",
        answerCorrect: "5",
      },
    ],
    avarageScore: 50,
    takeTime: "flexible",
    questionsOrder: "random",
  },
  {
    id: "3",
    title: "Science Fundamentals",
    instructor: instructors[1],

    instructions: "Answer these science questions. Images may be included.",
    randomizeQuestions: false,
    immediateFeedback: true,
    feedbackByEmail: false,
    timeLimit: 150,
    passingScore: 75,
    retakeNumbers: 3,
    questions: [
      {
        id: "q5",
        type: "multiple-choice",
        text: "Which planet is known as the Red Planet?",
        imageUrl:
          "https://science.nasa.gov/wp-content/uploads/2023/09/mars-gallery-1-1-jpg.webp",
        points: 5,
        options: [
          { id: "q5-o1", text: "Venus", isCorrect: false },
          { id: "q5-o2", text: "Mars", isCorrect: true },
          { id: "q5-o3", text: "Jupiter", isCorrect: false },
          { id: "q5-o4", text: "Saturn", isCorrect: false },
        ],
        explanation: "Mars appears red due to iron oxide on its surface.",
        answerCorrect: 1,
      },
      {
        id: "q6",
        type: "true-false",
        text: "Water boils at 100°C at sea level.",
        points: 3,
        options: [
          { id: "q6-true", text: "True", isCorrect: true },
          { id: "q6-false", text: "False", isCorrect: false },
        ],
        explanation:
          "At standard atmospheric pressure (1 atm), water boils at 100°C.",
        answerCorrect: 0,
      },
    ],
    avarageScore: 70,
    takeTime: "flexible",
    questionsOrder: "random",
  },
  {
    id: "4",
    title: "History Trivia",
    instructions: "Test your knowledge of historical events and figures.",
    randomizeQuestions: true,
    immediateFeedback: false,
    feedbackByEmail: true,
    instructor: instructors[4],
    timeLimit: 180,
    passingScore: 65,
    retakeNumbers: 2,
    questions: [
      {
        id: "q7",
        type: "multiple-choice",
        text: "Who was the first president of the United States?",
        imageUrl: "https://i.ytimg.com/vi/x8t3HWcIBqQ/maxresdefault.jpg",
        points: 5,
        options: [
          {
            id: "q7-o1",
            text: "Thomas Jefferson",
            imageUrl: "https://i.ytimg.com/vi/x8t3HWcIBqQ/maxresdefault.jpg",
            isCorrect: false,
          },
          {
            id: "q7-o2",
            text: "George Washington",
            imageUrl: "https://i.ytimg.com/vi/x8t3HWcIBqQ/maxresdefault.jpg",
            isCorrect: true,
          },
          {
            id: "q7-o3",
            text: "Abraham Lincoln",
            imageUrl: "https://i.ytimg.com/vi/x8t3HWcIBqQ/maxresdefault.jpg",
            isCorrect: false,
          },
          {
            id: "q7-o4",
            text: "John Adams",
            imageUrl: "https://i.ytimg.com/vi/x8t3HWcIBqQ/maxresdefault.jpg",
            isCorrect: false,
          },
        ],
        explanation: "George Washington served from 1789 to 1797.",
        answerCorrect: 1,
      },
      {
        id: "q8",
        type: "short-answer",
        text: "In what year did World War II end?",
        points: 5,
        explanation: "World War II ended in 1945 with the surrender of Japan.",
        answerCorrect: "1945",
      },
    ],
    avarageScore: 90,
    takeTime: "flexible",
    questionsOrder: "random",
  },
  {
    id: "5",
    title: "Literature Challenge",
    instructions: "Questions about famous books and authors.",
    randomizeQuestions: false,
    immediateFeedback: true,
    feedbackByEmail: false,
    instructor: instructors[1],
    timeLimit: 120,
    passingScore: 70,
    retakeNumbers: 3,
    questions: [
      {
        id: "q9",
        type: "multiple-choice",
        text: "Who wrote 'Pride and Prejudice'?",
        points: 5,
        options: [
          { id: "q9-o1", text: "Charlotte Brontë", isCorrect: false },
          { id: "q9-o2", text: "Jane Austen", isCorrect: true },
          { id: "q9-o3", text: "Emily Dickinson", isCorrect: false },
          { id: "q9-o4", text: "Virginia Woolf", isCorrect: false },
        ],
        explanation: "Jane Austen published Pride and Prejudice in 1813.",
        answerCorrect: 1,
      },
      {
        id: "q10",
        type: "true-false",
        text: "Shakespeare wrote 'The Odyssey'.",
        points: 3,
        options: [
          { id: "q10-true", text: "True", isCorrect: false },
          { id: "q10-false", text: "False", isCorrect: true },
        ],
        explanation: "The Odyssey was written by Homer, not Shakespeare.",
        answerCorrect: 1,
      },
    ],
    avarageScore: 30,
    takeTime: "flexible",
    questionsOrder: "random",
  },
];
