import { RoleBasedLinks } from "@/types";
import { MessageOutlined } from "@mui/icons-material";
import {
  Bell,
  BookCheck,
  BookOpen,
  BriefcaseBusiness,
  Calendar,
  DollarSign,
  FilePlus,
  FileQuestion,
  FileStack,
  GraduationCap,
  Info,
  LayoutDashboard,
  LibraryBig,
  MessageCircle,
  MessageCircleWarning,
  Search,
  Settings,
  ShoppingCart,
  Users,
  File,
  Building2,
  CalendarClock,
  CirclePercent,
  ReceiptText,
  User,
  Megaphone,
  Wallet,
  Boxes,
  FileUser,
  PackagePlus,
  Package,
  BookPlus,
  Book,
  CalendarPlus,
  Newspaper,
  UserPlus2,
  Users2,
  NotebookPen,
  BookCopy,
  FileCog,
  Building,
  SquarePlus,
  UserCog,
  Tickets,
  Award,
  CircleQuestionMark,
  Star,
  Heart,
} from "lucide-react";

export const roleBasedSideBarLinks: RoleBasedLinks = {
  admin: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
      permissions: [],
    },
    {
      id: 1,
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/admin",
      permissions: [],
    },
    {
      id: 2,
      label: "Courses",
      icon: BookCheck,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Courses",
          icon: LibraryBig,
          path: "/admin/courses",
          pattern: "/admin/courses/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Course",
          icon: FilePlus,
          path: "/lms/course/add",
          type: "supLink",
          permissions: [],
        },
        {
          id: 3,
          label: "Course settings",
          icon: FileCog,
          path: "/admin/course-settings",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 3,
      label: "Quizzes",
      icon: File,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Quizzes",
          icon: FileStack,
          path: "/admin/quizzes",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Quiz 1",
          icon: FilePlus,
          path: "/lms/add-quiz-1",
          type: "supLink",
          permissions: [],
        },
        {
          id: 3,
          label: "New Quiz 2",
          icon: FilePlus,
          path: "/lms/add-quiz-2",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 4,
      label: "Assignments",
      icon: NotebookPen,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Assignments",
          icon: BookCopy,
          path: "/admin/assignments",
          type: "supLink",
          permissions: [],
        },
        // {
        //   id: 2,
        //   label: "New Assignment",
        //   icon: BookPlus,
        //   path: "/admin/add-assignment",
        //   type: "supLink",
        //   permissions: [],
        // },
      ],
      permissions: [],
    },
    {
      id: 5,
      label: "Users Management",
      icon: Users2,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "Instructors Team",
          icon: Users2,
          path: "/admin/instructors-team",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "Medicova Teams",
          icon: Users2,
          path: "/admin/employees",
          type: "supLink",
          permissions: [],
        },
        {
          id: 3,
          label: "New User",
          icon: UserPlus2,
          path: "/admin/users",
          type: "supLink",
          permissions: [],
        },
        {
          id: 4,
          label: "User Settings",
          icon: UserCog,
          path: "/admin/departments",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 6,
      label: "Students",
      icon: GraduationCap,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Students",
          icon: GraduationCap,
          path: "/admin/students",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Student",
          icon: UserPlus2,
          path: "/admin/add-student",
          type: "supLink",
          permissions: [],
        },
        {
          id: 3,
          label: "Enrollments",
          icon: BookOpen,
          path: "/admin/students/enrollment",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 7,
      label: "Instructors",
      icon: Users2,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Instructors",
          icon: Users2,
          path: "/admin/instructors",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Instructor",
          icon: UserPlus2,
          path: "/admin/add-instructors",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 8,
      label: "Academies",
      icon: Building,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Academies",
          icon: Building2,
          path: "/admin/academies",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Academy",
          icon: SquarePlus,
          path: "/admin/add-academy",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 10,
      label: "Financial-1",
      path: "/admin/financial",
      icon: Building2,
      permissions: [],
    },
    {
      id: 11,
      label: "Financial-2",
      path: "/admin/financial",
      icon: Building2,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "Transactions",
          icon: FilePlus,
          path: "/admin/transactions",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "Billing & Subscribtion",
          icon: Newspaper,
          path: "/admin/plans",
          type: "supLink",
          permissions: [],
        },
        {
          id: 3,
          label: "Withdrawals",
          icon: Wallet,
          path: "/admin/withdrawal.",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 12,
      label: "Invoices",
      path: "/admin/financial",
      icon: Newspaper,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Invoices",
          icon: FilePlus,
          path: "/admin/invoices",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Invoice",
          icon: Newspaper,
          path: "/admin/add-invoice",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 13,
      label: "Events",
      icon: CalendarClock,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "Events",
          icon: CalendarClock,
          path: "/admin/events",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Event",
          icon: CalendarPlus,
          path: "/admin/add-event",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },

    {
      id: 14,
      label: "Tickets",
      path: "/admin/tickets",
      icon: Tickets,
      permissions: [],
    },
    {
      id: 15,
      label: "Testimonials",
      path: "/admin/testimonials",
      icon: Award,
      permissions: [],
    },
    {
      id: 16,
      label: "Reviews",
      path: "/admin/reviews",
      icon: Star,
      permissions: [],
    },
    {
      id: 17,
      label: "FAQs",
      path: "/admin/faqs",
      icon: CircleQuestionMark,
      permissions: [],
    },
    {
      id: 18,
      label: "Blogs",
      path: "/admin/blog",
      icon: Newspaper,
      permissions: [],
    },
    {
      id: 19,
      label: "Report",
      path: "#",
      icon: MessageCircleWarning,
      permissions: [],
    },
    {
      id: 20,
      label: "Chat",
      icon: MessageCircle,
      path: "/chat",
      notifications: 3,
      permissions: [],
    },
    {
      id: 21,
      icon: Bell,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
      permissions: [],
    },
    {
      id: 22,
      type: "text",
      section: "Recourses",
      permissions: [],
    },
    {
      id: 23,
      label: "Question Bank",
      path: "/admin/events",
      icon: FileQuestion,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "MCQ Packages",
          icon: Package,
          path: "/admin/prometric-exams",
          pattern: "/admin/prometric-exams/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Package",
          icon: PackagePlus,
          path: "/admin/add-package",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 24,
      label: "Books",
      icon: Book,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Books",
          icon: LibraryBig,
          path: "/admin/books",
          pattern: "/admin/books/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Book",
          icon: BookPlus,
          path: "/admin/add-book",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 25,
      label: "Digital Products",
      icon: Package,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "All Products",
          icon: Package,
          path: "/admin/products",
          pattern: "/admin/products/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "New Products",
          icon: PackagePlus,
          path: "/admin/add-Product",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 26,
      type: "text",
      section: "Settings",
      permissions: [],
    },
    {
      id: 27,
      label: "Site Settings",
      icon: Settings,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "Content",
          icon: FilePlus,
          path: "/admin/site-settings/content",
          pattern: "/admin/site-settings/content/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 2,
          label: "Branding",
          icon: Settings,
          path: "/admin/site-settings/branding",
          pattern: "/admin/site-settings/branding/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 3,
          label: "SEO Manager",
          icon: Search,
          path: "/admin/site-settings/seo",
          pattern: "/admin/site-settings/seo/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 4,
          label: "Snippets",
          icon: File,
          path: "/admin/site-settings/Snippets",
          pattern: "/admin/site-settings/Snippets/*",
          type: "supLink",
          permissions: [],
        },
        {
          id: 5,
          label: "Tools",
          icon: Boxes,
          path: "/admin/site-settings/tools",
          pattern: "/admin/site-settings/tools/*",
          type: "supLink",
          permissions: [],
        },
      ],
      permissions: [],
    },
    {
      id: 28,
      label: "Settings",
      icon: Settings,
      path: "#",
      permissions: [],
    },
    {
      id: 29,
      label: "Settings2",
      icon: Settings,
      path: "/admin/settings2",
      permissions: [],
    },
    {
      id: 30,
      label: "Help Center",
      path: "#",
      icon: BriefcaseBusiness,
      permissions: [],
    },
  ],
  default: [],
  instructor: [
    {
      id: 0,
      permissions: [],
      type: "profile",
      pattern: "/in/[id]",
    },
    {
      id: 1,
      permissions: [],
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/instructor/dashboard",
    },
    {
      id: 3,
      permissions: [],
      label: "Courses",
      icon: BookCheck,
      type: "collapse",
      links: [
        {
          id: 1,
          permissions: [],
          label: "Manage Courses",
          icon: LibraryBig,
          path: "/instructor/courses",
          pattern: "/instructor/courses/*",
          type: "supLink",
        },
        {
          id: 2,
          permissions: [],
          label: "Add New Course",
          icon: FilePlus,
          path: "/lms/course/add",
          type: "supLink",
        },
        {
          id: 3,
          permissions: [],
          label: "Manage Bundels",
          icon: LibraryBig,
          path: "/instructor/bundles",
          pattern: "/instructor/bundles/*",
          type: "supLink",
        },
        {
          id: 4,
          permissions: [],
          label: "Add new Bundle",
          icon: FilePlus,
          path: "/lms/bundle/add",
          type: "supLink",
        },
        {
          id: 5,
          permissions: [],
          label: "Coupons",
          icon: CirclePercent,
          path: "/instructor/coupons",
          type: "supLink",
        },
      ],
    },
    {
      id: 4,
      permissions: [],
      label: "Quizzes",
      icon: FileQuestion,
      type: "collapse",
      links: [
        {
          id: 1,
          permissions: [],
          label: "Manage Quizzes",
          icon: FileStack,
          path: "/instructor/quizzes",
          type: "supLink",
        },
        {
          id: 2,
          permissions: [],
          label: "Add New Quiz 1",
          icon: FilePlus,
          path: "/lms/add-quiz-1",
          type: "supLink",
        },
        {
          id: 3,
          permissions: [],
          label: "Add New Quiz 2",
          icon: FilePlus,
          path: "/lms/add-quiz-2",
          type: "supLink",
        },
      ],
    },
    {
      id: 5,
      permissions: [],
      label: "Invoices",
      icon: ReceiptText,
      type: "collapse",
      links: [
        {
          id: 1,
          permissions: [],
          label: "Manage Invoices",
          icon: ReceiptText,
          path: "/instructor/invoices",
          type: "supLink",
        },
        {
          id: 2,
          permissions: [],
          label: "Add New Invoice",
          icon: ReceiptText,
          path: "/lms/add-invoice",
          type: "supLink",
        },
      ],
    },
    {
      id: 6,
      permissions: [],
      label: "Assigments",
      icon: LibraryBig,
      path: "/instructor/assignments",
    },
    {
      id: 7,
      permissions: [],
      label: "Groups",
      icon: Boxes,
      path: "/instructor/groups",
    },
    {
      id: 8,
      permissions: [],
      label: "Students",
      icon: Users,
      path: "/instructor/students",
    },
    {
      id: 9,
      permissions: [],
      label: "Financial",
      icon: DollarSign,
      path: "/instructor/financial",
    },
    {
      id: 10,
      permissions: [],
      label: "Schedule",
      icon: Calendar,
      path: "/instructor/schedule",
    },
    {
      id: 11,
      permissions: [],
      label: "Withdrawal",
      icon: Wallet,
      path: "/instructor/withdrawal",
    },
    {
      id: 12,
      permissions: [],
      label: "Announcements",
      icon: Megaphone,
      path: "/instructor/announcements",
    },
    {
      id: 13,
      permissions: [],
      label: "Report",
      path: "#",
      icon: MessageCircleWarning,
    },
    {
      id: 14,
      permissions: [],
      label: "Chat",
      icon: MessageCircle,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 15,
      permissions: [],
      icon: Bell,
      label: "Notifications",
      path: "#",
      notifications: 4,
    },
    {
      id: 16,
      permissions: [],
      type: "text",
      section: "Settings",
    },
    {
      id: 17,
      permissions: [],
      label: "Settings",
      icon: Settings,
      path: "/instructor/settings",
    },
    {
      id: 18,
      permissions: [],
      label: "Help Center",
      icon: Info,
    },
  ],
  academy_admin: [
    {
      id: 0,
      permissions: [],
      type: "profile",
      pattern: "/ac/[id]",
    },
    {
      id: 1,
      permissions: [],
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/instructor/dashboard",
    },
    {
      id: 3,
      permissions: [],
      label: "Courses",
      icon: BookCheck,
      type: "collapse",
      links: [
        {
          id: 1,
          permissions: [],
          label: "Manage Courses",
          icon: LibraryBig,
          path: "/instructor/courses",
          pattern: "/instructor/courses/*",
          type: "supLink",
        },
        {
          id: 2,
          permissions: [],
          label: "Add New Course",
          icon: FilePlus,
          path: "/lms/course/add",
          type: "supLink",
        },
        {
          id: 3,
          permissions: [],
          label: "Manage Bundels",
          icon: LibraryBig,
          path: "/instructor/bundles",
          pattern: "/instructor/bundles/*",
          type: "supLink",
        },
        {
          id: 4,
          permissions: [],
          label: "Add new Bundle",
          icon: FilePlus,
          path: "/lms/bundle/add",
          type: "supLink",
        },
        {
          id: 5,
          permissions: [],
          label: "Coupons",
          icon: CirclePercent,
          path: "/instructor/coupons",
          type: "supLink",
        },
      ],
    },
    {
      id: 4,
      permissions: [],
      label: "Quizzes",
      icon: FileQuestion,
      type: "collapse",
      links: [
        {
          id: 1,
          permissions: [],
          label: "Manage Quizzes",
          icon: FileStack,
          path: "/instructor/quizzes",
          type: "supLink",
        },
        {
          id: 2,
          permissions: [],
          label: "Add New Quiz 1",
          icon: FilePlus,
          path: "/lms/add-quiz-1",
          type: "supLink",
        },
        {
          id: 3,
          permissions: [],
          label: "Add New Quiz 2",
          icon: FilePlus,
          path: "/lms/add-quiz-2",
          type: "supLink",
        },
      ],
    },
    {
      id: 19,
      permissions: [],
      label: "Instructors",
      icon: Users,
      path: "/academy/instructors",
      pattern: "/academy/instructors/*",
    },
    {
      id: 20,
      permissions: [],
      label: "Academy Users",
      icon: Users,
      path: "/academy/users",
      pattern: "/academy/users/*",
    },
    {
      id: 5,
      permissions: [],
      label: "Finance",
      icon: ReceiptText,
      type: "collapse",
      links: [
        {
          id: 0,
          permissions: [],
          label: "Overview",
          icon: ReceiptText,
          path: "/instructor/financial",
          type: "supLink",
        },
        {
          id: 1,
          permissions: [],
          label: "Transactions",
          icon: ReceiptText,
          path: "/instructor/transactions",
          type: "supLink",
        },
        {
          id: 2,
          permissions: [],
          label: "Withdrawals",
          icon: ReceiptText,
          path: "/instructor/withdrawal",
          type: "supLink",
        },
        {
          id: 3,
          permissions: [],
          label: "Plans",
          icon: ReceiptText,
          path: "/instructor/plans",
          type: "supLink",
        },
      ],
    },
    {
      id: 6,
      permissions: [],
      label: "Assigments",
      icon: LibraryBig,
      path: "/instructor/assignments",
    },
    {
      id: 7,
      permissions: [],
      label: "Groups",
      icon: Boxes,
      path: "/instructor/groups",
    },
    {
      id: 8,
      permissions: [],
      label: "Students",
      icon: Users,
      path: "/instructor/students",
    },
    {
      id: 10,
      permissions: [],
      label: "Schedule",
      icon: Calendar,
      path: "/instructor/schedule",
    },
    {
      id: 12,
      permissions: [],
      label: "Announcements",
      icon: Megaphone,
      path: "/instructor/announcements",
    },
    {
      id: 13,
      permissions: [],
      label: "Report",
      path: "#",
      icon: MessageCircleWarning,
    },
    {
      id: 14,
      permissions: [],
      label: "Chat",
      icon: MessageCircle,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 15,
      permissions: [],
      icon: Bell,
      label: "Notifications",
      path: "#",
      notifications: 4,
    },
    {
      id: 16,
      permissions: [],
      type: "text",
      section: "Settings",
    },
    {
      id: 17,
      permissions: [],
      label: "Settings",
      icon: Settings,
      path: "/instructor/settings",
    },
    {
      id: 18,
      permissions: [],
      label: "Help Center",
      icon: Info,
    },
  ],
  student: [
    {
      id: 1,
      permissions: [],
      type: "profile",
    },
    {
      id: 2,
      permissions: [],
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/student/dashboard",
    },
    {
      id: 4,
      permissions: [],
      label: "Profile",
      icon: User,
      pattern: "/st/[id]",
    },

    {
      id: 5,
      permissions: [],
      icon: LibraryBig,
      label: "My Courses",
      path: "/student/my-courses",
    },
    {
      id: 6,
      permissions: [],
      icon: Heart,
      label: "Saved Courses",
      path: "/student/favorite",
      pattern: "/student/favorite/*",
    },
    {
      id: 7,
      permissions: [],
      label: "Explore Courses",
      icon: Search,
      path: "/courses",
      pattern: "/courses/*",
    },
    {
      id: 8,
      permissions: [],
      label: "Browse Instructors",
      icon: Users,
      path: "/student/browse-instructors",
      pattern: "/student/browse-instructors/*",
    },
    {
      id: 9,
      permissions: [],
      label: "Assignments",
      icon: File,
      path: "/student/assignments",
      pattern: "/student/assignments/*",
    },
    {
      id: 10,
      permissions: [],
      label: "Referrals",
      icon: FileUser,
      path: "/student/referrals",
      pattern: "/student/referrals/*",
    },
    {
      id: 11,
      permissions: [],
      icon: Calendar,
      label: "Schedule ",
      path: "/student/schedule",
      notifications: 4,
    },
    {
      id: 12,
      permissions: [],
      icon: Bell,
      label: "Notifications",
      path: "#",
      notifications: 4,
    },
    {
      id: 13,
      permissions: [],
      icon: ShoppingCart,
      label: "Cart",
      path: "/cart",
      notifications: 4,
    },
    {
      id: 14,
      permissions: [],
      icon: Wallet,
      label: "Payment",
      path: "/student/payment-getway",
      pattern: "/student/payment-getway/*",
    },
    {
      id: 15,
      permissions: [],
      icon: MessageCircle,
      label: "Messages",
      path: "/chat",
      notifications: 4,
    },

    {
      id: 16,
      permissions: [],
      section: "Settings",
      type: "text",
    },
    {
      id: 17,
      permissions: [],
      icon: Settings,
      label: "Settings",
      path: "/student/settings",
    },
    {
      id: 18,
      permissions: [],
      icon: Info,
      label: "Help Center",
      path: "#",
    },
  ],
  unverified: [
    {
      id: 0,
      label: "Verify Account",
      icon: MessageOutlined,
      notifications: 1,
      path: "/auth/verify",
      pattern: "/auth/verify",
      permissions: [],
    },
  ],
};
