import {
  PlansReport,
  SubscriptionPlan,
  TransactionType,
} from "@/types/finance";

export const TOP_REVENUE_PLANS: PlansReport[] = [
  {
    id: "1",
    name: "Business",
    price: 26000,
    purchases: 50,
    employers: 30,
    revenue: 50 * 26000, // 1,300,000 EGP
    status: "active",
  },
  {
    id: "2",
    name: "Pro",
    price: 5500,
    purchases: 120,
    employers: 100,
    revenue: 120 * 5500, // 660,000 EGP
    status: "active",
  },
  {
    id: "3",
    name: "Basic",
    price: 3500,
    purchases: 180,
    employers: 100,
    revenue: 180 * 3500, // 630,000 EGP
    status: "active",
  },
  {
    id: "4",
    name: "Free",
    price: 0,
    purchases: 700,
    employers: 300,
    revenue: 0, // 630,000 EGP
    status: "active",
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "4",
    name: "Free",
    description: "Start for free and explore basic features",
    highlight: false,
    badge: "Free Forever",
    duration: 1,
    price: 0,
    vat: 20,
    vatDescription: "No VAT — this plan is completely free.",
    currency: "EGP",
    discountedPrice: 0,
    features: [
      { name: "Unlimited Profile Views", tag: "new" },
      { name: "10 Candidate Unlocks" },
      { name: "1 Job Posting" },
      { name: "1 User Seat" },
      {
        name: "Access unlocked profiles for 1 month extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 10,
    jobs: 1,
    invitations: 5,
    users: 1,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 1,
  },
  {
    id: "3",
    name: "Basic",
    description: "Ideal for small teams with light hiring needs",
    highlight: false,
    duration: 1,
    price: 3990,
    discountedPrice: 3500,
    vat: 14,
    vatDescription:
      "Subtotal: EGP 3,500\nVAT (14%): EGP 490\nTotal: EGP 3,990 (inclusive of VAT)",
    currency: "EGP",
    features: [
      { name: "Unlimited Profile Views" },
      { name: "30 Candidate Unlocks" },
      { name: "5 Job Postings", tag: "new" },
      { name: "2 User ", tag: "new" },
      {
        name: "Access unlocked profiles for 1 month extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 30,
    jobs: 5,
    invitations: 10,
    users: 2,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 1,
  },
  {
    id: "2",
    name: "Pro",
    description: "Perfect for companies hiring 1–2 roles monthly",
    highlight: false,
    badge: "Most Popular",
    vat: 20,
    duration: 6,
    price: 6270,
    discountedPrice: 5500,
    vatDescription:
      "Subtotal: EGP 5,500\nVAT (14%): EGP 770\nTotal: EGP 6,270 (includes all taxes)",
    currency: "EGP",
    features: [
      { name: "Unlimited Profile Views" },
      { name: "150 Candidate Unlocks" },
      { name: "20 Job Postings", tag: "new" },
      { name: "3 User " },
      { name: "Priority Support", tag: "new" },
      {
        name: "Access unlocked profiles for 3 months extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 150,
    jobs: 20,
    invitations: 60,
    users: 3,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 3,
  },
  {
    id: "1",
    name: "Business",
    description: "Designed for teams with active or high-volume hiring",
    highlight: true,
    badge: "Best Value",
    vat: 20,
    duration: 12,
    price: 29640,
    discountedPrice: 26000,
    vatDescription:
      "Subtotal: EGP 26,000\nVAT (14%): EGP 3,640\nTotal Payable: EGP 29,640 (all-inclusive)",
    currency: "EGP",
    features: [
      { name: "Unlimited Profile Views", tag: "new" },
      { name: "400 Candidate Unlocks" },
      { name: "30 Job Postings" },
      { name: "10 User " },
      { name: "Featured & Premium Support" },
      {
        name: "Access unlocked profiles for 6 months extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 400,
    jobs: 30,
    invitations: 150,
    users: 10,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 6,
  },
];

export const TRANSACTIONS: TransactionType[] = [
  {
    id: "1",
    invoice_id: "INV_2025_001",
    created_at: "13 July, 2021",
    payment_method: "VISA",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Jack",
    },
    total_amount: 29.99,
    download_receipt_url: "",
  },
  {
    id: "2",
    invoice_id: "INV_2025_002",
    created_at: "13 July, 2021",
    payment_method: "PayPal",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Sarah",
    },
    total_amount: 9.99,
    download_receipt_url: "",
  },
  {
    id: "3",
    invoice_id: "INV_2025_003",
    created_at: "22 September, 2021",
    payment_method: "VISA",
    type: "add-on",
    planId: "",
    plan: "",
    employer: {
      username: "#",
      image: "",
      name: "Mike",
    },
    total_amount: 19.99,
    download_receipt_url: "",
  },
  {
    id: "4",
    invoice_id: "INV_2025_004",
    created_at: "30 October, 2021",
    payment_method: "PayPal",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Emma",
    },
    total_amount: 9.99,
    download_receipt_url: "",
  },
  {
    id: "5",
    invoice_id: "INV_2025_005",
    created_at: "5 November, 2021",
    payment_method: "MasterCard",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Liam",
    },
    total_amount: 39.99,
    download_receipt_url: "",
  },
  {
    id: "6",
    invoice_id: "INV_2025_006",
    created_at: "15 December, 2021",
    payment_method: "Stripe",
    type: "add-on",
    planId: "",
    plan: "",
    employer: {
      username: "#",
      image: "",
      name: "Sophia",
    },
    total_amount: 14.99,
    download_receipt_url: "",
  },
  {
    id: "7",
    invoice_id: "INV_2025_007",
    created_at: "3 January, 2022",
    payment_method: "VISA",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Oliver",
    },
    total_amount: 9.99,
    download_receipt_url: "",
  },
  {
    id: "8",
    invoice_id: "INV_2025_008",
    created_at: "20 February, 2022",
    payment_method: "PayPal",
    type: "subscription",
    planId: "2",
    plan: "Pro",
    employer: {
      username: "#",
      image: "",
      name: "Ava",
    },
    total_amount: 24.99,
    download_receipt_url: "",
  },
  {
    id: "9",
    invoice_id: "INV_2025_009",
    created_at: "10 March, 2022",
    payment_method: "Bank Transfer",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Ethan",
    },
    total_amount: 49.99,
    download_receipt_url: "",
  },
  {
    id: "10",
    invoice_id: "INV_2025_010",
    created_at: "25 April, 2022",
    payment_method: "Stripe",
    type: "add-on",
    planId: "",
    plan: "",
    employer: {
      username: "#",
      image: "",
      name: "Isabella",
    },
    total_amount: 19.99,
    download_receipt_url: "",
  },
  {
    id: "11",
    invoice_id: "INV_2025_011",
    created_at: "12 May, 2022",
    payment_method: "MasterCard",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Noah",
    },
    total_amount: 39.99,
    download_receipt_url: "",
  },
  {
    id: "12",
    invoice_id: "INV_2025_012",
    created_at: "8 June, 2022",
    payment_method: "VISA",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Mia",
    },
    total_amount: -9.99,
    download_receipt_url: "",
  },
];
