import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import DynamicHeader from "@/components/Layout/Header/Header";
import DynamicLayout from "@/components/Layout/layout";
import { NextAuthProvider } from "@/NextAuthProvider";
import { Suspense } from "react";
import HeaderSelector from "@/components/Layout/Header/SelectedHeader";
import SideBar from "@/components/Layout/SideBar/SideBar";
import DynamicSideBar from "@/components/Layout/SideBar/dynamic-side-bar";
import { Toaster } from "sonner";
import ThemeProviderClient from "./ThemeProviderClient";

const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-poppins", // Custom CSS variable
});
// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   weight: ["400", "500", "600", "700"],
// });

export const metadata = {
  title: "Medicova",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} font-poppins bg-background`}>
        <StoreProvider>
          <ThemeProviderClient>
            <NextAuthProvider>
              <Suspense fallback={<HeaderSelector />}>
                <DynamicHeader />
              </Suspense>
              <DynamicLayout>
                <Suspense fallback={<DynamicSideBar />}>
                  <SideBar />
                </Suspense>
                <div className="flex-1">{children}</div>
              </DynamicLayout>
              <Toaster />
            </NextAuthProvider>
          </ThemeProviderClient>
        </StoreProvider>
      </body>
    </html>
  );
}
